GET http://localhost:5000

###
POST http://localhost:5000/api/v1/user/signup
Content-Type: application/json

{
  "username": "abc",
  "password": "123456",
  "confirmPassword": "123456",
  "displayName": "quyendv"
}

###
POST http://localhost:5000/api/v1/user/signin
Content-Type: application/json

{
  "username": "abc",
  "password": "123456"
}

### 
GET http://localhost:5000/api/v1/user/info
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4NDUxNjg5NSwiZXhwIjoxNjg0NjAzMjk1fQ.GHtqSy4wc71JdR95GWLODK9_CxFibRtAiv423anuaxY

###
PUT http://localhost:5000/api/v1/user/update-password
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

{
  "password": "123456",
  "newPassword": "123123",
  "confirmPassword": "123123"
}

###
GET http://localhost:5000/api/v1/user/favorites
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

###
POST http://localhost:5000/api/v1/user/favorites
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

{
  "mediaType": "movie",
  "mediaId": 123,
  "mediaTitle": "Title movie",
  "mediaPoster": "url poster",
  "mediaRate": 7.8
}

###
DELETE http://localhost:5000/api/v1/user/favorites/645ff96165ca61dd62c3d103
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

###
GET http://localhost:5000/api/v1/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjhiM2E0NGU5OWQyZDZiOGVhNWNiNSIsImlhdCI6MTY4NDgzODY0MSwiZXhwIjoxNjg0OTI1MDQxfQ.fG6hxbK2LhqgxGnKqoaOo-Mbm1wpfk36kgPvXJzvnws

###
GET http://localhost:5000/api/v1/comments/385687

###
POST http://localhost:5000/api/v1/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjhiM2E0NGU5OWQyZDZiOGVhNWNiNSIsImlhdCI6MTY4NDgzODY0MSwiZXhwIjoxNjg0OTI1MDQxfQ.fG6hxbK2LhqgxGnKqoaOo-Mbm1wpfk36kgPvXJzvnws

{
  "mediaId": "385687",
  "content": "new new!",
  "mediaType": "movie",
  "mediaTitle": "Fast X",
  "mediaPoster": "/1E5baAaEse26fej7uHcjOgEE2t2.jpg"
}

###
DELETE http://localhost:5000/api/v1/comments/646b3f3606674e2c84694730
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjhiM2E0NGU5OWQyZDZiOGVhNWNiNSIsImlhdCI6MTY4NDc0NjEyMSwiZXhwIjoxNjg0ODMyNTIxfQ.qGm2Eaptcs3K6sud6UZ2ShlBIgVht699_Fqk0C4prBw

###
GET http://localhost:5000/api/v1/media/favorite/823999
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NjhiM2E0NGU5OWQyZDZiOGVhNWNiNSIsImlhdCI6MTY4NDY4MjI2NSwiZXhwIjoxNjg0NzY4NjY1fQ.bUFbHHZGn4wUfIQ5qzZA4FFY7OZcC86FIaZGPmhOGe0