GET http://localhost:5000

###
POST http://localhost:5000/api/v1/user/signup
Content-Type: application/json

{
  "username": "abc",
  "password": "123456",
  "confirmPassword": "123456",
  "displayName": "quyendv"
}

###
POST http://localhost:5000/api/v1/user/signin
Content-Type: application/json

{
  "username": "abc",
  "password": "123456"
}

### 
GET http://localhost:5000/api/v1/user/info
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

###
PUT http://localhost:5000/api/v1/user/update-password
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

{
  "password": "123456",
  "newPassword": "123123",
  "confirmPassword": "123123"
}

###
GET http://localhost:5000/api/v1/user/favorites
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

###
POST http://localhost:5000/api/v1/user/favorites
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

{
  "mediaType": "movie",
  "mediaId": 123,
  "mediaTitle": "Title movie",
  "mediaPoster": "url poster",
  "mediaRate": 7.8
}

###
DELETE http://localhost:5000/api/v1/user/favorites/645ff96165ca61dd62c3d103
Content-Type: application/json
Authorization: Bear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4Mzk2ODMxMiwiZXhwIjoxNjg0MDU0NzEyfQ.qaHcqHdY-tsZqkT6STOf6Fzqs7WJkwQo1MCT5qiRMY4

###
GET http://localhost:5000/api/v1/comments/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4NDI0ODg5NCwiZXhwIjoxNjg0MzM1Mjk0fQ.sr8keYBaka0JSZ4ozJiDuKyfG1bq_xHdRShedBvFofo

###
GET http://localhost:5000/api/v1/comments/12345
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4NDI0ODg5NCwiZXhwIjoxNjg0MzM1Mjk0fQ.sr8keYBaka0JSZ4ozJiDuKyfG1bq_xHdRShedBvFofo

###
POST http://localhost:5000/api/v1/comments/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4NDI0ODg5NCwiZXhwIjoxNjg0MzM1Mjk0fQ.sr8keYBaka0JSZ4ozJiDuKyfG1bq_xHdRShedBvFofo

{
  "mediaId": "12345",
  "content": "comment",
  "mediaType": "movie",
  "mediaTitle": "Title movie",
  "mediaPoster": "url poster"
}

###
DELETE http://localhost:5000/api/v1/comments/6460ca60f177836be0311d43
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NWUyM2YyYzY4MDM0YzRmNDM1OGJkMSIsImlhdCI6MTY4NDI0ODg5NCwiZXhwIjoxNjg0MzM1Mjk0fQ.sr8keYBaka0JSZ4ozJiDuKyfG1bq_xHdRShedBvFofo
